vich_uploader:
    db_driver: orm

    mappings:
        posts_images:
            uri_prefix: /images/posts
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            upload_destination: '%kernel.project_dir%/public/images/posts'
